package kmlio

import (
	"archive/zip"
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/zoobst/gobi"
)

// kmzPrimaryEntry is the conventional name of the primary KML file
// inside a KMZ archive. gobi's writer always emits under this name;
// the reader prefers it too but falls back to the first .kml entry
// for archives produced by other tools.
const kmzPrimaryEntry = "doc.kml"

// resolveReadFormat picks the effective on-disk format for a
// ReadFile call. Explicit opts.Format wins; FormatAuto falls back to
// extension inspection. Unknown extensions default to FormatKML —
// KML files often have no extension at all (they're sometimes
// unzipped inline from a KMZ during development).
func resolveReadFormat(path string, opts *ReadOptions) Format {
	if opts != nil && opts.Format != FormatAuto {
		return opts.Format
	}
	if strings.EqualFold(filepath.Ext(path), ".kmz") {
		return FormatKMZ
	}
	return FormatKML
}

// resolveWriteFormat is the write-side equivalent. Same rules.
func resolveWriteFormat(path string, opts *WriteOptions) Format {
	if opts != nil && opts.Format != FormatAuto {
		return opts.Format
	}
	if strings.EqualFold(filepath.Ext(path), ".kmz") {
		return FormatKMZ
	}
	return FormatKML
}

// readKMZFile opens path as a zip archive and reads the primary KML
// entry into a Frame. Uses zip.OpenReader to avoid buffering the
// whole file — most KMZ archives are small enough that this
// doesn't matter much, but the streaming API is available and
// costs nothing to use.
func readKMZFile(path string, opts *ReadOptions) (*gobi.Frame, error) {
	zr, err := zip.OpenReader(path)
	if err != nil {
		return nil, fmt.Errorf("%w: open kmz: %v", ErrInvalidKML, err)
	}
	defer zr.Close()
	return readKMZFromReader(&zr.Reader, opts)
}

// readKMZReader handles the io.Reader path for KMZ. archive/zip
// requires a random-access reader with a known size, so we buffer
// the full input first. This is fine for typical KMZ sizes (up to
// tens of MB); callers streaming very large KMZ archives should
// use ReadFile against the file directly.
func readKMZReader(r io.Reader, opts *ReadOptions) (*gobi.Frame, error) {
	var buf bytes.Buffer
	if _, err := io.Copy(&buf, r); err != nil {
		return nil, fmt.Errorf("%w: buffer kmz: %v", ErrInvalidKML, err)
	}
	zr, err := zip.NewReader(bytes.NewReader(buf.Bytes()), int64(buf.Len()))
	if err != nil {
		return nil, fmt.Errorf("%w: parse kmz: %v", ErrInvalidKML, err)
	}
	return readKMZFromReader(zr, opts)
}

// readKMZFromReader locates the primary .kml entry inside a
// zip.Reader and delegates to the plain-KML XML decoder. Prefers
// "doc.kml" (the spec convention) but accepts any .kml file when
// the primary is missing — matches ogr2ogr / QGIS behavior on
// non-standard KMZ archives.
func readKMZFromReader(zr *zip.Reader, opts *ReadOptions) (*gobi.Frame, error) {
	entry := pickKMLEntry(zr)
	if entry == nil {
		return nil, fmt.Errorf("%w: no .kml entry in kmz", ErrInvalidKML)
	}
	rc, err := entry.Open()
	if err != nil {
		return nil, fmt.Errorf("%w: open %q: %v", ErrInvalidKML, entry.Name, err)
	}
	defer rc.Close()
	return readXML(rc, opts)
}

// pickKMLEntry returns the primary KML entry inside a KMZ archive.
// Prefers "doc.kml" per KMZ convention; falls back to the first
// .kml file at any depth. Case-insensitive extension match so
// archives with .KML entries still parse.
func pickKMLEntry(zr *zip.Reader) *zip.File {
	var fallback *zip.File
	for _, f := range zr.File {
		if strings.EqualFold(f.Name, kmzPrimaryEntry) {
			return f
		}
		if fallback == nil && strings.EqualFold(filepath.Ext(f.Name), ".kml") {
			fallback = f
		}
	}
	return fallback
}

// writeKMZFile creates a KMZ archive at path containing a single
// entry named "doc.kml" with the KML content generated by
// writeXML. Uses os.Create for cleanest disk-write semantics
// (truncate + open); atomically-replaced-on-success would need a
// temp-file dance we don't bother with today.
func writeKMZFile(f *gobi.Frame, path string, opts *WriteOptions) error {
	out, err := os.Create(path)
	if err != nil {
		return err
	}
	defer out.Close()
	return writeKMZ(f, out, opts)
}

// writeKMZ streams a KMZ archive to w — one deflate-compressed
// entry ("doc.kml") holding the KML XML. archive/zip.Writer needs
// only an io.Writer (not io.WriteSeeker) so this path streams
// without buffering the whole archive.
func writeKMZ(f *gobi.Frame, w io.Writer, opts *WriteOptions) error {
	zw := zip.NewWriter(w)
	entry, err := zw.CreateHeader(&zip.FileHeader{
		Name:   kmzPrimaryEntry,
		Method: zip.Deflate,
	})
	if err != nil {
		return fmt.Errorf("kmz: create entry: %w", err)
	}
	if err := writeXML(f, entry, opts); err != nil {
		return fmt.Errorf("kmz: write kml: %w", err)
	}
	if err := zw.Close(); err != nil {
		return fmt.Errorf("kmz: close archive: %w", err)
	}
	return nil
}
